[package]
name = "rs_sdf"
version = "0.1.0"
authors = ["Karuma <info@karuma.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.3"
